### PR TITLE
[fix] Set pkg type to `module`

### PR DESCRIPTION
**Pull request by yqrashawn**
since it's using `import` in index.js
this may fail tests running with node

### CODE REVIEW

**Comment by HwangTaehyun** [comment]
Thanks for your attention!

**Comment by HwangTaehyun** [comment]
Would you change your commit title to **[fix] Set pkg type to module**?
Thanks!

**Comment by HwangTaehyun** [comment]
ping @yqrashawn. What do you think about participating hacktoberfest?

**Comment by yqrashawn** [comment]
> ping @yqrashawn. What do you think about participating [hacktoberfest](https://hacktoberfest.com/)?

I don't think I have the time

**Comment by HwangTaehyun** [comment]
@yqrashawn Okay, Thanks! Could you change only the commit title? Then I merged this PR now!

**Comment by yqrashawn** [comment]
@HwangTaehyun I changed the commit message. Sorry for the delay.

**Pull request merged**
